[package]
name = "vocabulator"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
rusqlite = { version = "0.31", features = ["bundled"] }
anyhow = "1"
ratatui = "0.26"
crossterm = "0.27"
